### ISSUE TITLE
Version in 'About Kotlin Explorer' is wrong

### ISSUE THREAD

**Issue by mhansen** [romainguy/kotlin-explorer#10]
To repro: 

1. Download version 0.8.2 https://github.com/romainguy/kotlin-explorer/releases/tag/v0.8.2
2. Open about menu (on mac: Kotlin Explorer menu --> About Kotlin Explorer)

Expected:
- Says version 0.8.2

Actual:
- Says version 1.0.0

![image](https://github.com/romainguy/kotlin-explorer/assets/105529/4f07463c-c69f-4e15-9eb8-6d25cde146f4)

Not a big deal or anything! Just like the tool, thought I'd start contributing ideas.

**Comment by romainguy** [comment]
Thanks! Yeah it's a known issue, because macOS refuses to let you set a version < 1.0.0 in your manifest. So right now the version as seen by macOS is different from the actual one 😓

**Comment by mhansen** [comment]
1.0.0 is hardcoded here: https://github.com/romainguy/kotlin-explorer/blob/cacd3b68bab8ce6f9021e83595a63673d1ddd9f0/build.gradle.kts#L63

**Comment by mhansen** [comment]
Wow, what a rude move by macOS to enforce v1+! I suppose let's just wait till a stable v1 release :-)
