### ISSUE TITLE
Publish to HomeBrew

### ISSUE THREAD

**Issue by Goooler** [romainguy/kotlin-explorer#52]
If we can publish the build artifact to [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) or a custom brew repo like [Jake's](https://github.com/JakeWharton/homebrew-repo)? It would be easier to track the version updates.

**Comment by romainguy** [comment]
Not sure. Kotlin Explorer requires the use of [JetBrains' Java runtime](https://github.com/JetBrains/JetBrainsRuntime).

**Comment by Goooler** [comment]
I addressed a PR to my repo at https://github.com/Goooler/homebrew-repo/pull/10, but seems Brew Casks can't depend on external dependencies.

**Comment by romainguy** [comment]
Can you deploy a DMG and its content via Homebrew? I'm not familiar with custom casks. If so, it's fine, the DMG already contains the JetBrains runtime.

**Comment by Goooler** [comment]
Seems this Cask could not be submitted to [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask) as 

```sh
brew audit --cask --new kotlin-explorer
==> Downloading and extracting artifacts
==> Downloading https://github.com/romainguy/kotlin-explorer/releases/download/v1.1.0/kotlin-explore
Already downloaded: /Users/goooler/Library/Caches/Homebrew/downloads/a967504a53c36f103411d7fe18b98f9947706e77e1975c9e2bceaed0b896874e--kotlin-explorer-1.1.0.dmg
==> Downloading https://github.com/romainguy/kotlin-explorer/releases/download/v1.1.0/kotlin-explore
Already downloaded: /Users/goooler/Library/Caches/Homebrew/downloads/a967504a53c36f103411d7fe18b98f9947706e77e1975c9e2bceaed0b896874e--kotlin-explorer-1.1.0.dmg
audit for kotlin-explorer: failed
 - Upstream defined :high_sierra as the minimum OS version and the cask defined no minimum OS version
 - Signature verification failed:
/private/tmp/cask-audit20240516-27504-ccen0l/Kotlin Explorer.app: rejected

macOS on ARM requires software to be signed.
Please contact the upstream developer to let them know they should sign and notarize their software.
goooler/repo/kotlin-explorer
  * Upstream defined :high_sierra as the minimum OS version and the cask defined no minimum OS version
  * line 5, col 2: Signature verification failed:
    /private/tmp/cask-audit20240516-27504-ccen0l/Kotlin Explorer.app: rejected

    macOS on ARM requires software to be signed.
    Please contact the upstream developer to let them know they should sign and notarize their software.
Error: 2 problems in 1 cask detected.
```

Similar issues like https://github.com/Homebrew/homebrew-cask/pull/173504#issuecomment-2106034208.

**Comment by Goooler** [comment]
As a workaround, users can try out 

```sh
brew install Goooler/repo/kotlin-explorer
```

this cask will be auto bumped by like https://github.com/Goooler/homebrew-repo/pull/11.
