### ISSUE TITLE
Support Mac x64

### ISSUE THREAD

**Issue by Goooler** [romainguy/kotlin-explorer#59]
This can't be running on Mac x64 devices, it's intended not to support them? May need to support x64 devices or note we only support arm64 devices in readme.

<img width="861" alt="image" src="https://github.com/romainguy/kotlin-explorer/assets/10363352/862df774-671c-4c1b-83f4-d30c0bc5b8d6">

**Comment by romainguy** [comment]
I don't have an Intel Mac so I can't work on this nor guarantee support. You can however do it yourself by compiling locally? You'll need an x64 version od thé Jetbrains runtime.

**Comment by Goooler** [comment]
I'll try to fix this...

**Comment by Goooler** [comment]
I'm trying to build dists on CI, but seems `packageDmg` tasks were skipped due to some runtimes missing.

See:

- https://github.com/Goooler/kotlin-explorer/commit/fba3b2da7a70a0f3570e70c1d1ca150fd93662bc
- https://github.com/Goooler/kotlin-explorer/actions/runs/9534059010/job/26278030530#step:5:57
