### ISSUE TITLE
No way to navigate back to settings once set

### ISSUE THREAD

**Issue by JakeWharton** [romainguy/kotlin-explorer#6]
Should probably be in the menu

**Comment by romainguy** [comment]
The current workaround it to delete the fil `~/.kotlin-explorer/settings`. The settings UI should also come back automatically if one of the paths becomes invalid.

**Comment by JakeWharton** [comment]
Yeah I went and just edited it manually to the right path.

**Comment by romainguy** [comment]
Fixed in v0.9.0.
