### ISSUE TITLE
Unable to compile/run the example code

### ISSUE THREAD

**Issue by erawhctim** [romainguy/kotlin-explorer#68]
Having an issue running the default sample that's listed immediately on opening the app. Have I misconfigured the settings somehow? (I have Kotlin intalled via homebrew):

![Screenshot 2024-08-15 at 4 50 42 PM](https://github.com/user-attachments/assets/70d54f09-282f-4a70-8c05-67e358abcadc)

I get this error on run:
```
Error: Main method not found in class KotlinExplorerKt, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
```

**Comment by erawhctim** [comment]
`/opt/homebrew/Cellar/kotlin/2.0.10` also seems to satisfy the field validation in the settings, but gives the same error. 

I'm probably missing something obvious? I'd be happy to contribute a small amendment into the README to make this more explicit

**Comment by romainguy** [comment]
The default example is not runnable, it doesn't have a main method. You can disassemble it though.

**Comment by erawhctim** [comment]
ah, so this works as expected! I had confused "run" to mean "run the disassemble process and give me something to look at" 🙂 thanks
