### ISSUE TITLE
Inline documentation for smali

### ISSUE THREAD

**Issue by EpicDima** [romainguy/kotlin-explorer#71]
In this commit https://github.com/romainguy/kotlin-explorer/commit/04e92d6841e6a3851b9a9d230404ef0ae0aaf9a0, a cool feature with documentation for ARM is made, it seems that something like this may be useful for smali (dex).

After searching a little, I found such a site https://maximoff.su/smali/?lang=en, where we can download everything in JSON format at the same time ([link](https://maximoff.su/smali/?act=json&from=en&r=1725487857)), like how the generation of ARM documentation is done.

**Comment by romainguy** [comment]
I find dex documentation less useful because the instruction names are pretty self explanatory. I also want folks to focus on the final arm code :)

**Comment by EpicDima** [comment]
Yeah, I got it, thanks)

**Comment by romainguy** [comment]
Note that I'm not against it if someone wanted to contribute this feature. Just wanted to set expectations of me doing it anytime soon.
