### ISSUE TITLE
Error when running on MacOS

### ISSUE THREAD

**Issue by jdavisAR** [romainguy/kotlin-explorer#73]
When running the following code in _Kotlin-Explorer_

```
public val Int.sign: Int get() = when {
    this < 0 -> -1
    this > 0 -> 1
    else -> 0
}
```

I get the following error:

> error: source file or directory not found: 

I've setup both the **Android home directory** and **Kotlin home directory**. As a test, I changed the Kt home dir and attempting a build the tool gave me file not found errors for several files contained in my original kt directory.

Here is a screenshot of my Settings:
<img width="1728" alt="Screenshot 2024-10-03 at 10 23 59 AM" src="https://github.com/user-attachments/assets/9f26e2f6-558a-45c5-bf9f-984126b0c6a5">

My machine is a 2023 **MacBook Pro**  M2 Max running macOS Sonoma 14.4.1

**Comment by brunohensel** [comment]
To fix this for my simple case, I checked whether the `compilerFlags` were not empty or blank before adding them to the command in the `KotlinCompiler` file. It appears that an empty/black flag causes the issue.

**Comment by jdavisAR** [comment]
> To fix this for my simple case, I checked whether the `compilerFlags` were not empty or blank before adding them to the command in the `KotlinCompiler` file. It appears that an empty/blank flag causes the issue.

What compiler flags are you using?

**Comment by brunohensel** [comment]
> > To fix this for my simple case, I checked whether the `compilerFlags` were not empty or blank before adding them to the command in the `KotlinCompiler` file. It appears that an empty/blank flag causes the issue.
> 
> What compiler flags are you using?

None. The compilerFlag was empty in my case.

**Comment by jdavisAR** [comment]
> > > To fix this for my simple case, I checked whether the `compilerFlags` were not empty or blank before adding them to the command in the `KotlinCompiler` file. It appears that an empty/blank flag causes the issue.
> > 
> > 
> > What compiler flags are you using?
> 
> None. The compilerFlag was empty in my case.

I understand what you mean. I will make the same change.

**Comment by jdavisAR** [comment]
> Thanks @brunohensel! @jdavisAR try with the patch that just landed. I couldn't reproduce the issue even though I don't have compiler flags defined.

Thanks @brunohensel!, that patch did fix the issue for me.
