### ISSUE TITLE
Error with Android home directory

### ISSUE THREAD

**Issue by JanMalch** [romainguy/kotlin-explorer#76]
I set up all the environment variables as documented.
But when I run the app (via `./gradlew jvmRun`) I get a red error icon next to the Android home directory. Is there any way to tell why it shows an error? Because the directory is actually correct and contains the expected folders as specified in the README.

I'm running on macOS and `$ANDROID_HOME = $HOME/Library/Android/sdk`.

**Comment by romainguy** [comment]
It looks for `platform-tools/adb`, `build-tools/dexdump`, and `lib/d8.jar` in the specified directory.
